services:
  gaz_con:
    image: humblegazebo
    environment:
      - DISPLAY=:0
      - XAUTHORITY=/tmp/.X11-unix/X0
    network_mode: host
    volumes:
      - ./SimulationFiles:/home/Catcher
      - /tmp/.X11-unix:/tmp/.X11-unix
    tty: true

volumes:
  SimulationFiles: